### PR TITLE
Update docker build action

### PR DESCRIPTION
**Pull request by Szarad**
Add step to update requirements,txt file for the Docker image.

### CODE REVIEW

**Review by lsmith77 — CHANGES_REQUESTED** [review]
I guess we can then delete https://github.com/witty-works/nlp_api/blob/dev/requirements.txt ?

**Comment by Szarad** [comment]
> I guess we can then delete https://github.com/witty-works/nlp_api/blob/dev/requirements.txt ?

Yes, that's right. I removed this file.

**Comment by lsmith77** [comment]
ok great .. can you also review the README.md ?

**Comment by Szarad** [comment]
> ok great .. can you also review the README.md ?

Yes, I updated it accordingly.

**Pull request merged**
