### PR TITLE
localize translations

### LINKED ISSUE #339: Localize Category Names
Generate localized versions of category.py for en-GB and de-CH

### PR DESCRIPTION
**Pull request by lsmith77**
fixes https://github.com/witty-works/nlp_api/issues/339

@Szarad maybe you have an idea here:
there is a problem I just noticed. the `eng` library does not handle any words with upper case letters, ie. "Organization" is not converted to "Organisation".

I don't have a good idea to change this, especially since I don't quite understand the code https://github.com/orsinium-labs/eng/blob/master/eng/_fixer.py and also I am not sure how one properly tests changes to libs.

* [ ] add instructions on how to patch dependency, https://github.com/orsinium-labs/eng/pull/1

### CODE REVIEW

**Comment by Szarad** [comment]
So I checked the code, from what I understood in `_replacement.py` file to get object from mapping one should use `lower()` function. I tested it,  works fine. @lsmith77  if you want to test it; in installation path for `eng` package in `_replacement.py ` file change line `27` to `new_word = words.get(old_word.lower())`

**Comment by lsmith77** [comment]
> So I checked the code, from what I understood in `_replacement.py` file to get object from mapping one should use `lower()` function. I tested it, works fine. @lsmith77 if you want to test it; in installation path for `eng` package in `_replacement.py ` file change line `27` to `new_word = words.get(old_word.lower())`

so I guess we would submit this a PR to the repo? is there a way to automate this patching until that is merged?

**Comment by Szarad** [comment]
> > So I checked the code, from what I understood in `_replacement.py` file to get object from mapping one should use `lower()` function. I tested it, works fine. @lsmith77 if you want to test it; in installation path for `eng` package in `_replacement.py ` file change line `27` to `new_word = words.get(old_word.lower())`
> 
> so I guess we would submit this a PR to the repo? is there a way to automate this patching until that is merged?

I created the PR. Regarding using own library for now, could you tell me where the original library is used? I only see mention in README to compile files locally, but can't find anything in deployment steps.

**Comment by lsmith77** [comment]
@Szarad I applied your patch for eng and re-ran the compile translation script. I goess this is now ready to be merged.

**Review by Szarad — APPROVED** [review]
Works fine for me.

**Pull request merged**
