### PR TITLE
add a max text length setting

### LINKED ISSUE #338: add limit for maximum text size

### PR DESCRIPTION
**Pull request by lsmith77**
fixes https://github.com/witty-works/nlp_api/issues/338

### CODE REVIEW

**Review by Szarad — COMMENTED** [review]
It is good to add this, but I have 2 concerns:
1. User text could be cut in the middle of the word
2. What with the rest of user's text? User gets some notification?

**Comment by lsmith77** [comment]
> It is good to add this, but I have 2 concerns:
> 
> 1. User text could be cut in the middle of the word
> 2. What with the rest of user's text? User gets some notification?

yeah you are right .. the PR was rushed.

**Comment by lsmith77** [comment]
> 1. User text could be cut in the middle of the word

I now check what the last word is that no longer fits into the limit and cut of there.

> 2. What with the rest of user's text? User gets some notification?

I added something to the response, which the UI could then show to the user

**Comment by lsmith77** [comment]
FTR https://wittyworks.slack.com/archives/C019JFEN4AJ/p1643272554018600?thread_ts=1643211374.015000&cid=C019JFEN4AJ

**Comment by lsmith77** [comment]
FYI I already set the env var on platform.sh to 2000 characters

**Review by Szarad — APPROVED** [review]
Thanks for adding extra response and handling text correctly! I played a bit with setting and tested it, looks good for me!

**Pull request merged**
