### PR TITLE
transform word to lowcase english

### PR DESCRIPTION
**Pull request by lnazarenko**
- Add GetLowerCased for English rules. Sometimes SpaCy struggle with lemmatisation of the words with capital letter and either transform them also to capital letter either transform them to not the right form of the word. To avoid this the function GetLowerCased for English rules was added. This issue related to [283](https://github.com/witty-works/nlp_api/issues/283), which was not completely resolved with stripe(). And also now it highlights "Head" in this dirty text "Thomas Jung\nHead of Talent Acquisition EMEA\n\nFossil Group Europe GmbH\nRiehenring 182\n\n4058 Basel\nSWITZERLAND"
- fix test correspondently

### CODE REVIEW

**Review by Szarad — COMMENTED** [review]
Could you changed names of the function from camel case to pythonic name?
`GetLowerCased` to `get_lower_cased` 
and `RulesBasedWordsPhraseMatcherEN` to `rules_based_words_phrase_matcher_en`

**Comment by lsmith77** [comment]
@Szarad maybe we should do this renaming of all the functions in a separate PR?

**Comment by lsmith77** [comment]
ah I see sonarcloud is complaining about the naming as well :)

**Comment by lsmith77** [comment]
@lnazarenko I guess this is the fix for https://github.com/witty-works/nlp_api/issues/331 ?

**Comment by lnazarenko** [comment]
@lsmith77 the issue 331 is related to "dirty" text. And here the issue regarding the sometimes wrong lemmatization of spacy with the words with capital letter. This PR fully fix this [283](https://github.com/witty-works/nlp_api/issues/283)

**Comment by Szarad** [comment]
Looks good to me, but shouldn't we get rid of rstrip() then? https://github.com/witty-works/nlp_api/blob/8040fab1a1b5d968885eba735940060e45c22113/app/main.py#L460  I tested it without, works good after your changes @lnazarenko

**Comment by lnazarenko** [comment]
@lsmith77 @Szarad I would keep rstrip() if it doesn't affect performance. It removes all unnecessary whitespace at the beginning and end of custom text, which could potentially cause other issues that we may not yet be aware of.

**Comment by Szarad** [comment]
I see, makes sense. Then all good from my side:)

**Pull request merged**
