### PR TITLE
capture context for cases where plural vs. singular cannot be determined

### LINKED ISSUE #415: capture context for cases where plural vs. singular cannot be determined
https://sentry.io/organizations/witty-works/issues/2950555300/?project=5991571&query=is%3Aunresolved&statsPeriod=14d

### PR DESCRIPTION
**Pull request by lsmith77**
fixes https://github.com/witty-works/nlp_api/issues/415

unfortunately we don't have a test case .. in fact the aim of this PR is to find a test case :)

### CODE REVIEW

**Comment by Szarad** [comment]
@lsmith77 I committed my proposition for test case (it will fail now, because capture cannot be determined). So should I commented it out for now from test_api.py? or change assert method to "wrong value" and we will update snapshot when it will be handled correctly?

**Review by Szarad — CHANGES_REQUESTED** [review]
@lsmith77 your changes are of course ok, but let's look at proposed test case and how we want to proceed with that.

**Comment by lsmith77** [comment]
I guess adding the wrong value so the test fails with a comment makes sense for now.

**Comment by Szarad** [comment]
I agree, we can always commented it later. I added logging and comment.

**Comment by lsmith77** [comment]
did you remember to push?

**Comment by Szarad** [comment]
yes, I need to figure out how to capture it in github action

**Comment by Szarad** [comment]
*I meant capture in pytest

**Comment by Szarad** [comment]
ok it's fixed now. From my point of view, we can merge and if we decide to disable this test, we can always do it :)

**Pull request merged**
