### PR TITLE
ability to use the v2 API without logging in

### LINKED ISSUE #606: show highlights when not logged in
As a User I want to see why I should log in and what I am missing if I am not logged in\.

<p></p>

Acceptance criteria:

- When not logged in, still highlight words in grey

- In the popover show the same content as in the popup until the user has logged in

<p></p>

Design:

<p></p>

Feel free to adapt the design Solveig if needed\. I created two different versions\. You can find the design here\.

<p></p>

<p></p>

Implementation Thoughts:

- On the API we need to support non\-logged in requests against the \/v2\/check endpoint

- In this case return `premium` as the \(sub\-\)category without any alternatives

- Frontend then essentially only needs to use the new highlight color and custom content in the popover \(similar to what we have in the popup when the user is not logged in\)

### PR DESCRIPTION
**Pull request by lsmith77**
fixes https://github.com/witty-works/nlp_api/issues/606

### CODE REVIEW

**Review by hellasol — APPROVED** [review]
when you merge this to dev, the extension won't work because of validation errors. Do you want to merge and then I push the fix?

**Comment by lsmith77** [comment]
well then maybe the better approach is to do all of this only for a v2.1 check endpoint

**Comment by hellasol** [comment]
> 

yes, good idea!

**Comment by lsmith77** [comment]
ok done

**Review by hellasol — APPROVED** [review]

**Pull request merged**
